### ISSUE TITLE
start Cud without any opened files, call plugin 'Blame cur line'- plugin crashes

### ISSUE THREAD

**Issue by Alexey-T** [ThaiDat/cuda_git_blame#21]
```
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_git_blame/__init__.py", line 53, in do_blame_current_line
    result = parse_blame_one_line(*git_blame(fn, line))
  File "/home/user/.config/cudatext/py/cuda_git_blame/gitutils.py", line 31, in git_blame
    return __git(params, cwd=os.path.dirname(path))
  File "/home/user/.config/cudatext/py/cuda_git_blame/gitutils.py", line 18, in __git
    result = subprocess.run(params, capture_output=True, startupinfo=startupinfo, cwd=cwd)
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: ''
ERROR: Exception in CudaText for do_blame_current_line: FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by ThaiDat** [comment]
Fixed by adding a message in status bar when users use Git Blame on untitled tab.
