### ISSUE TITLE
error on Linux

### ISSUE THREAD

**Issue by Alexey-T** [ThaiDat/cuda_git_blame#4]
```
Init: cuda_git_blame
Traceback (most recent call last):
  File "/home/user/.config/cudatext/py/cuda_git_blame/__init__.py", line 41, in do_blame_current_line
    result = parse_blame_one_line(*git_blame(fn, line))
  File "/home/user/.config/cudatext/py/cuda_git_blame/gitutils.py", line 13, in git_blame
    startupinfo = subprocess.STARTUPINFO()
AttributeError: module 'subprocess' has no attribute 'STARTUPINFO'
ERROR: Exception in CudaText for do_blame_current_line: AttributeError: module 'subprocess' has no attribute 'STARTUPINFO'
```

**Comment by Alexey-T** [comment]
fix:
```python
    # startupinfo to prevent external console window appear
    if os.name=='nt':
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW
    else:
        startupinfo = None
```

**Comment by ThaiDat** [comment]
Yeah, thanks. I didn't test on Linux yet
