### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by veksha** [ThaiDat/cuda_git_blame#6]
```js
Traceback (most recent call last):
  File "F:\MySSDPrograms\cudatext\py\cuda_git_blame\__init__.py", line 52, in do_blame_analyze
    result = parse_blame_analysis(*git_blame(fn))
  File "F:\MySSDPrograms\cudatext\py\cuda_git_blame\parser.py", line 76, in parse_blame_analysis
    committer_time = int(committer_time)
ValueError: invalid literal for int() with base 10: b'<zulufaka.ms@gmail.com>'
ERROR: Exception in CudaText for do_blame_analyze: ValueError: invalid literal for int() with base 10: b'<zulufaka.ms@gmail.com>'
```

**Comment by veksha** [comment]
command `Blame analyze file`

**Comment by ThaiDat** [comment]
Can you help me run  and send me the result. It seems I missed some special edge cases
```
git blame yourfile --line-porcelain
```

**Comment by Alexey-T** [comment]
Log for ATFlatControls, history.txt
[log.txt](https://github.com/ThaiDat/cuda_git_blame/files/11287782/log.txt)

**Comment by ThaiDat** [comment]
Thanks. I made a patch, tested on ATFlatControls/history.txt, CudaText/formmain.pas.
